app:
  name: ObscuraTrace
  version: 1.0
  environment: production

api:
  solanatracker_url: 'https://data.solanatracker.io/trace/'
  rugcheck_url: 'https://api.rugcheck.xyz/trace/'

features:
  scam_detection: true
  wallet_monitoring: true
  risk_heatmap: true
  ai_insights: true
  anomaly_alerts: true

thresholds:
  scam_score: 70               # minimum score to flag as scam
  min_tx_count: 10             # minimum txs to include in analysis
  volume_spike: 50000          # USD volume spike threshold
  liquidity_drain_percent: 30  # % liquidity drop threshold
  anomaly_zscore: 3.0          # z-score cutoff for outliers
  whale_inactivity_duration: 3600000  # ms of no whale moves
  sybil_pattern_score: 60      # Sybil detection score cutoff

param_0: 0
param_1: 10
param_2: 20
param_3: 30
param_4: 40
param_5: 50
param_6: 60
param_7: 70
param_8: 80
param_9: 90
param_10: 100
param_11: 110
param_12: 120
param_13: 130
param_14: 140
